<?php
/**
 * Its Coupon rule model
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package Vite_Coupon_Lite\Libs
 */

namespace Vite_Coupon_Lite\libs;

use Automattic\WooCommerce\Utilities\NumberUtil;
use Decimal\Decimal;


/**
 * Class Coupon Rules
 *
 * @package VitePos\Libs
 */
class Coupon_Rules {

	/**
	 * Its property minimum_spend.
	 *
	 * @var double
	 */
	public $minimum_spend = '';
	/**
	 * Its maximum_spend.
	 *
	 * @var double
	 */
	public $maximum_spend = '';
	/**
	 * Its property is_individual.
	 *
	 * @var boolean
	 */
	public $is_indvidual = 'Y';
	/**
	 * Its property is_exclude_sale.
	 *
	 * @var boolean
	 */
	public $is_exclude_sale = 'Y';
	/**
	 * Its property is_free_shipping.
	 *
	 * @var boolean
	 */
	public $is_free_shipping = 'Y';
	/**
	 * Its property products.
	 *
	 * @var array
	 */
	public $products = array();
	/**
	 * Its property exclude_products.
	 *
	 * @var array
	 */
	public $exclude_products = array();
	/**
	 * Its property categories.
	 *
	 * @var array
	 */
	public $categories = array();
	/**
	 * Its property exclude_categories.
	 *
	 * @var array
	 */
	public $exclude_categories = array();
	/**
	 * Its property allowed_email.
	 *
	 * @var array
	 */
	public $allowed_emails = array();

	/**
	 * The set from array is generated by appsbd
	 *
	 * @param mixed $rules It is r param.
	 */
	public function set_from_array( $rules = array() ) {
		foreach ( $rules as $prop => $val ) {
			if ( property_exists( $this, $prop ) ) {
				$this->{$prop} = $val;
			}
		}
	}
}
