<?php
/**
 * It's for Coupon Category module
 *
 * @package Vite_Coupon_Lite\Modules
 */

namespace Vite_Coupon_Lite\Modules;

use Vite_Coupon_Lite\Models\Database\Mapbd_Coupon_Category;
use Appsbd_Lite\V2\Core\BaseModule;
use Appsbd_Lite\V2\libs\Ajax_Confirm_Response;
use Appsbd_Lite\V2\libs\Ajax_Data_Response;
use Appsbd_Lite\V2\libs\AppInput;

/**
 * Class Coupon_Category
 */
class Vite_Coupon_Category extends BaseModule {
	/**
	 * To initialize is generated by appsbd
	 */
	public function initialize() {
	}

	/**
	 * The on active is generated by appsbd
	 */
	public function on_active() {
		parent::on_active();
		Mapbd_Coupon_Category::create_db_table();
	}

	/**
	 * The on init is generated by appsbd
	 */
	public function on_init() {
		parent::on_init();
		$this->add_ajax_action( 'add-category', array( $this, 'add_category' ) );
		$this->add_ajax_action( 'get-categories', array( $this, 'get_categories' ) );
		$this->add_ajax_action( 'get-category', array( $this, 'get_category' ) );
		$this->add_ajax_action( 'delete-category', array( $this, 'delete_category' ) );
		$this->add_ajax_action( 'update-category', array( $this, 'update_category' ) );
		$this->add_ajax_action( 'change-status', array( $this, 'change_status' ) );
	}


	/**
	 * The Coupon category add is generated by appsbd
	 */
	public function add_category() {
		$response = new Ajax_Confirm_Response();
		if ( APPSBD_IS_POST_BACK ) {
			$nobject = new Mapbd_Coupon_Category();
			if ( $nobject->set_from_post_data( true ) ) {
				if ( $nobject->Save() ) {
					$this->add_info( 'Successfully added' );
					$response->display_with_response( true, $nobject );
					return;
				}
			}
		}
		$response->display_with_response( false );
	}



	/**
	 * The get Coupon categories is generated by appsbd
	 */
	public function get_categories() {
		$main_response = new Ajax_Data_Response();
		$mainobj       = new Mapbd_Coupon_Category();

		$mainobj->set_search_by_param( $main_response->src_by, 'title,slug' );
		$mainobj->set_sort_by_param( $main_response->sort_by );
		$records = $mainobj->count_aLL();
		if ( $records > 0 ) {
			$main_response->set_grid_records( $records );
			$result = $mainobj->select_all_grid_data(
				'',
				'',
				'',
				$main_response->limit,
				$main_response->limit_start()
			);
			$main_response->set_grid_data( $result );
		}

		$main_response->display_grid_response();
	}
	/**
	 * The Coupon category edit is generated by appsbd
	 */
	public function update_category() {
		$response    = new Ajax_Confirm_Response();
		$category_id = AppInput::request_value( 'id' );
		if ( empty( $category_id ) ) {
			$this->add_error( 'Invalid request' );
			$response->display_with_response( false );
			return;
		}

		if ( APPSBD_IS_POST_BACK ) {
			$uobject = new Mapbd_Coupon_Category();
			if ( $uobject->set_from_post_data( false ) ) {
				$uobject->unset_all_excepts( 'title,description,status' );
				$uobject->set_where_update( 'id', $category_id );
				if ( $uobject->update() ) {
					$this->add_info( 'Successfully updated' );
					$response->display_with_response( true, $uobject );
					return;
				}
			}
		}
		$response->display_with_response( false );
	}
	/**
	 * The Coupon category edit is generated by appsbd
	 */
	public function get_category() {
		$response    = new Ajax_Confirm_Response();
		$category_id = AppInput::post_value( 'category_id' );
		if ( empty( $category_id ) ) {
			$this->add_error( 'Invalid request' );
			$response->display_with_response( false );
			return;
		}

		$details = new Mapbd_Coupon_Category();
		$details->id( $category_id );
		if ( $details->select() ) {
			$response->display_with_response( true, $details );
		} else {
			$this->add_error( 'No category found with these ids' );
			$response->display_with_response( false, null );
		}
	}
	/**
	 * The Coupon category delete is generated by appsbd
	 */
	public function delete_category() {
		$param         = AppInput::post_value( 'category_id' );
		$main_response = new Ajax_Confirm_Response();
		if ( empty( $param ) ) {
			$this->add_error( 'Invalid Request' );
			$main_response->display_with_response( false );
			return;
		}
		$mr = new Mapbd_Coupon_Category();
		$mr->id( $param );
		if ( $mr->select() ) {
			if ( Mapbd_Coupon_Category::delete_by_id( $param ) ) {
				$this->add_info( 'Successfully deleted' );
				$main_response->display_with_response( true );
			} else {
				$this->add_error( 'Delete failed try again' );
				$main_response->display_with_response( false );
			}
		}
	}
	  /**
	   * The Coupon category change status is generated by appsbd
	   */
	public function change_status() {
		$category_id = AppInput::post_value( 'category_id' );
		$status      = AppInput::post_value( 'status' );
		$response    = new Ajax_Confirm_Response();
		if ( APPSBD_IS_POST_BACK ) {
			$nobject = new Mapbd_Coupon_Category();
			$nobject->status( $status );
			$nobject->set_where_update( 'id', $category_id );
			if ( $nobject->update() ) {
				$this->add_info( 'Successfully status changed' );
				$response->display_with_response( true );
				return;
			}
		}
		$response->display_with_response( false );
	}
}
