<?php
/**
 * It helper of global helper for both version.
 *
 * @package  vitepos
 */

if ( ! function_exists( 'appsbd_get_date_time_format' ) ) {
	/**
	 * The apbd get date time format is generated by appsbd
	 *
	 * @return string
	 */
	function appsbd_get_date_time_format() {
		return get_option( 'date_format' ) . ' ' . get_option( 'time_format' );
	}
}

if ( ! function_exists( 'appsbd_get_date_format' ) ) {
	/**
	 * The apbd get date format is generated by appsbd
	 *
	 * @return false|mixed|void
	 */
	function appsbd_get_date_format() {
		return get_option( 'date_format' );
	}
}


if ( ! function_exists( 'appsbd_wc_amount' ) ) {
	/**
	 * The vitepos wc amount is generated by appsbd
	 *
	 * @param mixed $amount Its amount param.
	 *
	 * @return float
	 */
	function appsbd_wc_amount( $amount ) {
		$amount = (float) $amount;
		$decimals = wc_get_price_decimals();
		return round( $amount, $decimals );
	}
}

if ( ! function_exists( 'appsbd_get_value_from_array' ) ) {
	/**
	 * Get value from array
	 *
	 * @param string $index Its index param.
	 * @param array  $arr Its array param.
	 * @param string $default Its default param.
	 */
	function appsbd_get_value_from_array( $index, &$arr, $default = '' ) {
		if ( isset( $arr[ $index ] ) ) {
			return $arr[ $index ];
		} else {
			return $default;
		}
	}
}
