<?php
/**
 * It helper of current plugin.
 *
 * @package  vitepos
 */

if ( ! function_exists( 'vite_coupon_get_outlets_key_val' ) ) {
	/**
	 * The get outlets key val is generated by appsbd
	 *
	 * @return array
	 */
	function vite_coupon_get_outlets_key_val() {
		/**
		 *
		 * Return all the outlets of vitepos.
		 *
		 * @since 1.0.0
		 *
		 * @var array $outlets
		 */
		$outlets    = apply_filters( 'vitepos/3rd-party/filter/outlets', array() );
		$return_obj = array();
		foreach ( $outlets as $value ) {
			$return_obj[ $value->id ] = $value->name;
		}
		return $return_obj;
	}
}



if ( ! function_exists( 'vite_coupon_has_wc' ) ) {
	/**
	 * Get value from array
	 */
	function vite_coupon_has_wc() {
		return appsbd_is_activated_plugin( 'woocommerce/woocommerce.php' );
	}
}

if ( ! function_exists( 'vite_coupon_is_inclusive_price' ) ) {
	/**
	 * Get value from array
	 */
	function vite_coupon_is_inclusive_price() {
		/**
		 * Its for check is the tax option is inclusive or exclusive.
		 *
		 * @since 3.0.4
		 */
		return apply_filters( 'woocommerce_prices_include_tax', get_option( 'woocommerce_prices_include_tax' ) === 'yes' );
	}
}

if ( ! function_exists( 'vite_date' ) ) {
	/**
	 * The vite date is generated by appsbd
	 *
	 * @param mixed $format It is format param.
	 * @param mixed $timestamp It is timestamp param.
	 *
	 * @return string
	 */
	function vite_date( $format, $timestamp = null ) {
		//phpcs:ignore
		return date( $format, $timestamp );
	}
}
