<?php
/**
 * Coupon_Plugin Coupons model
 *
 * @package Appsbd_Deal_lite\Models\Database
 */

namespace Vite_Coupon_Lite\Models\Database;

use Vite_Coupon_Lite\Core\Coupon_Lite_Model;

use Appsbd_Lite\V2\Core\BaseModel;

/**
 * Class Mapbd_Coupon_Settings
 *
 * @package Coupon_Plugin\Models\Database
 */
class Mapbd_Coupon_Settings extends Coupon_Lite_Model {

	/**
	 * Its property id
	 *
	 * @var int
	 */
	public $id;
	/**
	 * Its property general_settings
	 *
	 * @var text
	 */
	public $general_settings;
	/**
	 * Its property usage_settings
	 *
	 * @var text
	 */
	public $usage_settings;
	/**
	 * Its property scheduler_settings
	 *
	 * @var text
	 */
	public $scheduler_settings;
	/**
	 * Its property role_settings
	 *
	 * @var text
	 */
	public $role_settings;
	/**
	 * Its property url_settings
	 *
	 * @var text
	 */
	public $url_settings;




	/**
	 * Settings constructor.
	 */
	public function __construct() {

		parent::__construct();
		$this->set_validation();
		$this->app_base_name = 'coupon-plugin';
	}
	/**
	 * The filter data is generated by appsbd
	 */
	public function filter_data() {

		if ( $this->is_set_prperty( 'general_settings' ) && ! is_string( $this->general_settings ) ) {
			$this->general_settings( serialize( $this->general_settings ) );
		}
		if ( $this->is_set_prperty( 'scheduler_settings' ) && ! is_string( $this->scheduler_settings ) ) {
			$this->scheduler_settings( serialize( $this->scheduler_settings ) );
		}
		if ( $this->is_set_prperty( 'usage_settings' ) && ! is_string( $this->usage_settings ) ) {
			$this->usage_settings( serialize( $this->usage_settings ) );
		}
		if ( $this->is_set_prperty( 'role_settings' ) && ! is_string( $this->role_settings ) ) {
			$this->role_settings( serialize( $this->role_settings ) );
		}
		if ( $this->is_set_prperty( 'url_settings' ) && ! is_string( $this->url_settings ) ) {
			$this->url_settings( serialize( $this->url_settings ) );
		}
	}

	/**
	 * The save is generated by appsbd
	 *
	 * @return bool
	 */
	public function save() {
		$this->filter_data();
		return parent::save();
	}

	/**
	 * The update is generated by appsbd
	 *
	 * @param mixed $not_limit It is not_limit param.
	 * @param mixed $is_show_msg It is is_show_msg param.
	 * @param mixed $dont_process_id_where_not_set It is $dont_process_id_where_not_set param.
	 * @return bool
	 */
	public function update( $not_limit = false, $is_show_msg = true, $dont_process_id_where_not_set = true ) {
		$this->filter_data();
		return parent::update(
			$not_limit,
			$is_show_msg,
			$dont_process_id_where_not_set
		);
	}
}
